autoload:
  sfMondongoPlugin_lib:
    name:           sfMondongoPlugin_lib
    path:           <?php echo realpath(dirname(__FILE__).'/../lib')."\n" ?>
    recursive:      true
    exclude:        [vendor]
